
export const MenuList = [
  {
    id: 1,
    name: "Pepperoni Pizza",
    image: "/images/pepperoni.jpg",
    categorie:"Pizza",
    description: "Une délicieuse pizza au pepperoni avec une généreuse couche de fromage fondu et une sauce tomate savoureuse.",
    price: 50,
  },
  {
    id: 2,
    name: "Margherita Pizza",
    image: "/images/margherita.jpg",
    categorie:"Pizza",
    description: "Une pizza classique avec une base de sauce tomate, mozzarella fraîche, et feuilles de basilic.",
    price: 25,
  },
  {
    id: 3,
    name: "PedroTech Special Pizza",
    image: "/images/pedrotechspecial.jpg",
    categorie:"Pizza",
    description: "Une pizza unique avec des ingrédients exclusifs pour un goût inoubliable.",
    price: 70,
  },
  {
    id: 4,
    name: "Vegan Pizza",
    image: "/images/vegan.jpg",
    categorie:"Pizza",
    description: "Une pizza végétalienne garnie de légumes frais et d'un fromage sans produits laitiers.",
    price: 30,
  },
  {
    id: 5,
    name: "Pineapple Pizza",
    image: "/images/pineapple.jpg",
    categorie:"Pizza",
    description: "Une pizza sucrée-salée avec de l'ananas juteux et des tranches de jambon.",
    price: 60,
  },
  {
    id: 6,
    name: "Expensive Pizza",
    image: "/images/expensive.jpg",
    categorie:"Pizza",
    description: "Une pizza luxueuse avec des ingrédients rares et raffinés, parfaite pour les grandes occasions.",
    price: 100,
  },
  {
    id: 7,
    name: "Classic Beef Burger",
    image: "/images/beefburger.jpg",
    categorie:"Burger",
    description: "Un burger juteux avec un steak de boeuf, fromage, salade, tomates et une sauce spéciale.",
    price: 40,
  },
  {
    id: 8,
    name: "Chicken Burger",
    image: "/images/chickenburger.jpg",
    categorie:"Burger",
    description: "Un burger croustillant avec filet de poulet pané, mayonnaise, laitue et cornichons.",
    price: 50,
  },
  {
    id: 9,
    name: "Veggie Burger",
    image: "/images/veggieburger.jpg",
    categorie:"Burger",
    description: "Un burger végétarien avec un steak de légumes, fromage végétalien et des légumes frais.",
    price: 40,
  },
  {
    id: 10,
    name: "Double Cheese Burger",
    image: "/images/doublecheeseburger.jpg",
    categorie:"Burger",
    description: "Un burger généreux avec deux steaks de boeuf, double fromage et sauce barbecue.",
    price: 80,
  },
  {
    id: 11,
    name: "Fish Burger",
    image: "/images/fishburger.jpg",
    categorie:"Burger",
    description: "Un burger au poisson avec filet de poisson croustillant, laitue et sauce tartare.",
    price: 50,
  },
   // Boissons
   {
    id: 12,
    name: "Coca-Cola",
    image: "/images/coca.jpg",
    categorie:"Boisson",
    description: "Une boisson gazeuse rafraîchissante au goût unique.",
    price: 15,
  },
  {
    id: 13,
    name: "Sprite",
    image: "/images/sprite.jpg",
    categorie:"Boisson",
    description: "Une boisson gazeuse citronnée idéale pour étancher votre soif.",
    price: 15,
  },
  {
    id: 14,
    name: "Fanta",
    image: "/images/fanta.jpg",
    categorie:"Boisson",
    description: "Une boisson pétillante à l'orange, pleine de saveurs fruitées.",
    price: 15,
  },
  {
    id: 15,
    name: "Eau Minérale",
    image: "/images/water.jpg",
    categorie:"Boisson",
    description: "Une bouteille d'eau minérale pure pour une hydratation saine.",
    price: 10,
  },
];

